#!/bin/bash

SDK_VERSION=SDK_10.0.10.118

ROOT_PATH=$(pwd)
OUT=./DA1469x-BUILD
mkdir $OUT
cd $OUT

cmake -G "Ninja" -DCMAKE_TOOLCHAIN_FILE=$ROOT_PATH/Toolchain-DA1469x.cmake -DCMAKE_BUILD_TYPE=Release -DSDK_VERSION=$SDK_VERSION -DROOT_PATH=$ROOT_PATH ../
